# Generated by Django 6.0 on 2026-06-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(help_text='Start location (e.g., Phoenix, AZ)', max_length=255)),
                ('end_location', models.CharField(help_text='End location (e.g., Los Angeles, CA)', max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('total_distance', models.FloatField(help_text='Total route distance in miles')),
                ('route_coordinates', models.JSONField(help_text='GeoJSON coordinates of the route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('available_tank_range', models.IntegerField(default=500, help_text='Max distance on full tank (miles)')),
                ('range_max', models.IntegerField(default=500)),
                ('mpg', models.IntegerField(default=10, help_text='Miles per gallon')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_per_gallon', models.FloatField(help_text='Price in USD')),
            ],
            options={
                'verbose_name': 'Fuel Stop',
                'verbose_name_plural': 'Fuel Stops',
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['city', 'state'], name='api_fuelsto_city_d8d23a_idx'), models.Index(fields=['price_per_gallon'], name='api_fuelsto_price_p_eb31e5_idx'), models.Index(fields=['latitude', 'longitude'], name='api_fuelsto_latitud_0a3b4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.route')),
                ('total_fuel_cost', models.FloatField(help_text='Total estimated fuel cost in USD')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_routes', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Optimized Route',
                'verbose_name_plural': 'Optimized Routes',
                'ordering': ['-created_at'],
            },
            bases=('api.route',),
        ),
        migrations.CreateModel(
            name='RouteFuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Order of this stop in the route')),
                ('distance_from_start', models.FloatField(help_text='Distance from route start to this stop (miles)')),
                ('fuel_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_with_this_stop', to='api.fuelstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='api.route')),
            ],
            options={
                'verbose_name': 'Route Fuel Stop',
                'verbose_name_plural': 'Route Fuel Stops',
                'ordering': ['route', 'stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
        migrations.CreateModel(
            name='OptimizedRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(help_text='Order of this stop in the route')),
                ('distance_from_start', models.FloatField(help_text='Distance from route start to this stop (miles)')),
                ('distance_to_destination', models.FloatField(help_text='Distance from this stop to final destination (miles)')),
                ('distance_traveled', models.FloatField(help_text='Distance traveled since last stop (miles)')),
                ('fuel_cost_here', models.FloatField(help_text='Fuel cost for next leg: (distance_traveled / mpg) * price_per_gallon')),
                ('selection_reason', models.TextField(help_text='Why this stop was selected (closest/cheapest/reachable)')),
                ('fuel_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimized_route_stops', to='api.fuelstop')),
                ('optimized_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops_optimized', to='api.optimizedroute')),
            ],
            options={
                'verbose_name': 'Optimized Route Stop',
                'verbose_name_plural': 'Optimized Route Stops',
                'ordering': ['optimized_route', 'stop_order'],
                'unique_together': {('optimized_route', 'stop_order')},
            },
        ),
    ]
