# Generated by Django 6.0 on 2026-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available_tank_range',
            field=models.IntegerField(default=500, help_text='Max distance on available tank (miles)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='range_max',
            field=models.IntegerField(default=500, help_text='Max range full tank (miles)'),
        ),
    ]
