# Generated by Django 6.0 on 2026-06-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vehicle_available_tank_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
