# Generated by Django 6.0 on 2026-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fuelstop_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstop',
            name='address',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_tank_range',
            field=models.IntegerField(default=500, help_text='Currently available tank range (miles)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='range_max',
            field=models.IntegerField(default=500, help_text='Max range on a full tank (miles)'),
        ),
    ]
